# Generated by Django 5.0 on 2026-02-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imo_number', models.CharField(max_length=50)),
                ('flag', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Docked', 'Docked')], max_length=50)),
            ],
        ),
    ]
