# Generated by Django 5.0 on 2026-02-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('INSPECTOR', 'inspector'), ('ENGINEER', 'engineer')], max_length=50),
        ),
    ]
