# Generated by Django 5.0 on 2026-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_maintainencejobs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainencejobs',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
