# Generated by Django 5.0 on 2026-02-13 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_maintainencejobs_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainencejobs',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
